# Generated by Django 4.0.4 on 2022-05-18 10:47

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profle_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='booklify/profile_pics/default_profile.png', upload_to=books.models.upload_to),
        ),
    ]
