# Generated by Django 4.0.4 on 2022-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_profile_profle_image_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='in_bookmarks',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='like',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='book',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='book',
            field=models.ManyToManyField(to='books.books'),
        ),
    ]
