# Generated by Django 4.0.4 on 2022-05-18 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_remove_bookmarks_in_bookmarks_remove_bookmarks_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='markbook',
            field=models.ManyToManyField(default=None, related_name='Markbook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
