# Generated by Django 4.0.1 on 2022-05-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_books_markbook_delete_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='popularity',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
