# Generated by Django 4.0.4 on 2022-06-04 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_alter_books_markbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='markbook',
            field=models.ManyToManyField(default=None, related_name='Markbook', to=settings.AUTH_USER_MODEL),
        ),
    ]
