# Generated by Django 4.0.4 on 2022-06-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_books_markbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
    ]
